### ISSUE TITLE
Sudo Keep-Alive

### ISSUE THREAD

**Issue by FinalAngel** [divio/osx-bootstrap#1]
Find a solution how to enter the sudo password only once without using sudo su (per command base)

**Comment by LaraCraft93** [comment]
Not solved the problem yet?

**Comment by FinalAngel** [comment]
sadly not @LaraCraft93

**Comment by dcondrey** [comment]
This issue seems as though it's been resolved.. no?

**Comment by FinalAngel** [comment]
@dcondrey it can still be an issue as sudo prompts for the password after some idle time

**Comment by dcondrey** [comment]
Issue resolved in merge request #11
